name: idf build

on:
  push:
    branches: [ "master" ]  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: idf_st7789

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: build test_apps
        run: docker run --rm -v ${{ github.workspace }}:/$PROJECT_NAME espressif/idf sh -c "
          cd $PROJECT_NAME/test_apps && idf.py set-target esp32s3 && idf.py build"

      - name: build jpeg examples
        run: docker run --rm -v ${{ github.workspace }}:/$PROJECT_NAME espressif/idf sh -c "
          cd $PROJECT_NAME/examples/jpeg && idf.py set-target esp32s3 && idf.py build"